# Template for config file /etc/klish/klishd.conf. It's used by klishd daemon.

# The klishd uses UNIX domain socket to receive connections. It will create an
# filesystem entry to allow clients to find connection point. By default klishd
# uses /tmp/klish-unix-socket path.
#UnixSocketPath=/tmp/klish-unix-socket

# The group to set on the UNIX socket. By default, the socket retains the group
# of the user starting the daemon. The upstream sysrepo project recommends using
# the 'sysrepo' group to allow access to CLI tools.
#SocketGroup=sysrepo

DBs=libxml2
